# -*- coding: utf-8 -*-
"""
/***************************************************************************
 KrystianAlgorytmy
                                 A QGIS plugin
 wtyczka algorytmowa 
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-08-21
        copyright            : (C) 2024 by Tomasz Mazuga
        email                : tmazuga@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Tomasz Mazuga'
__date__ = '2024-08-21'
__copyright__ = '(C) 2024 by Tomasz Mazuga'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load KrystianAlgorytmy class from file KrystianAlgorytmy.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .algorytmy_krystiana import KrystianAlgorytmyPlugin
    return KrystianAlgorytmyPlugin()
